# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171110_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='longueur_analyse_energie',
            field=models.FloatField(default=0.02),
        ),
        migrations.AlterField(
            model_name='document',
            name='longueur_analyse_harmonique_frequence_fondamentale',
            field=models.FloatField(default=0.02),
        ),
        migrations.AlterField(
            model_name='document',
            name='longueur_fenetre_formant',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='document',
            name='pas_analyse_energie',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='document',
            name='pas_analyse_harmonique_frequence_fondamentale',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='document',
            name='pas_analyse_segmentation',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='document',
            name='seuil_segmentation',
            field=models.FloatField(default=0.15),
        ),
    ]
