# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171121_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='longueur_analyse_energie',
        ),
        migrations.RemoveField(
            model_name='document',
            name='longueur_analyse_harmonique_frequence_fondamentale',
        ),
        migrations.RemoveField(
            model_name='document',
            name='longueur_fenetre_formant',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pas_analyse_energie',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pas_analyse_harmonique_frequence_fondamentale',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pas_analyse_segmentation',
        ),
        migrations.RemoveField(
            model_name='document',
            name='seuil_segmentation',
        ),
        migrations.AddField(
            model_name='document',
            name='nickname',
            field=models.CharField(default='nickname', max_length=100),
        ),
    ]
